# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5f621d0a43144f0fd92ab9416652c321"
name = "wishlist-inspire"
handle = "wishlist-inspire-162"
application_url = "https://wishlist-organized-save-interviews.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "princetwotechies.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://wishlist-organized-save-interviews.trycloudflare.com/auth/callback",
  "https://wishlist-organized-save-interviews.trycloudflare.com/auth/shopify/callback",
  "https://wishlist-organized-save-interviews.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
